before:
  hooks: []

project_name: subcheck

release:
  prerelease: auto  # 自动识别 beta、rc 作为预发布

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    binary: >-
      {{ .ProjectName }}_linux_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "arm64" }}arm64
      {{- else }}{{ .Arch }}{{ end }}
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.CurrentCommit={{ .ShortCommit }}

archives: []

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch 